common: &common
    :asset_host: "http://www.dev.malmo.se/assets-2.0"
    :salt_length: 10
    :request_key_length: 20
    :generated_password_length: 8
    :occasion_reminder_days: 2
    :evaluation_form:
        :activation_days: 2
        :reminder_days: 7
    :ticket_state:
        :group_days: 14
        :district_days: 14
    :upload_attachment:
        :path: uploads/attachments
    :upload_image:
        :path: model
        :width: 454
        :height: 340
        :thumb_width: 204
        :thumb_height: 153
    :kp_external_link: "http://www.malmo.se/kulturproceduren"
    :kp_manual_link: "http://www.malmo.se/Medborgare/Kultur--noje/Barn--unga/Kultur-till-forskolor-och-skolor/Anvandarhjalp-till-Kulturproceduren.html"
    :kbu_link: "http://www.malmo.se/Medborgare/Kultur--noje/Barn--unga/Kultur-till-forskolor-och-skolor.html"
    :culture_bus_link: "http://www.malmo.se/Medborgare/Kultur--noje/Barn--unga/Kultur-till-forskolor-och-skolor/Kulturbussarna.html"
    #:ldap:
    #    :address:
    #    :port: 389
    #    :base_dn:
    #    :bind:
    #        :dn:
    #        :password:
    #    :max_search_results: 25
    #    :username_prefix: "malmoaut-"
    #:httpauth:
    #    :auth_url: "https://www.malmo.se/4.48c74f1f1249b31458c800013298/12.48c74f1f1249b31458c800013337.txt"
    #    :username_prefix: "malmoaut-"
    :allotment:
        :proximity_boundary: 3
    # OBS - se även config/enviroments/*rb actionmailer-config ... From-address måste anges även där
    :mailers:
        :from_adress: "Kulturproceduren, Malmö Stad <noreply@malmo.se>"
    :elit_kp_service_endpoint: "http://localhost:9080/elit-kpService/elit-kpPort"
        
development:
    <<: *common
    :instance_title: "DEV"
    :evaluation_form:
        :activation_days: 1
        :reminder_days: 2
    :ticket_state:
        :group_days: 1
        :district_days: 1
    :occasion_reminder_days: 1
    :mailers:
        :debug_recipient: "camilla.bengtsson@malmo.se"

test:
    <<: *common
release_test:
    <<: *common

production:
    <<: *common
    :asset_host: "http://www.malmo.se/assets-2.0"

education:
    <<: *common
    :instance_title: "UTB"
    :asset_host: "http://www.malmo.se/assets-2.0"

staging:
    <<: *common
    :instance_title: "STAGING"
    :instance_message: "Detta är en förberedelseinstans inför nästa termin. Förändringar här kommer inte att visas på malmo.se utan manuell handpåläggning av tekniker."
    :asset_host: "http://www.malmo.se/assets-2.0"

archive:
    <<: *common
    :instance_title: "ARKIV"
    :instance_message: "Detta är en arkivinstans för föregående läsår. Inga ändringar här kommer att kunna flyttas till malmo.se."
    :asset_host: "http://www.malmo.se/assets-2.0"

