development:
    :salt_length: 10
    :upload_image_path: images/model
test:
    :salt_length: 10
    :upload_image_path: images/model
production:
    :salt_length: 10
    :upload_image_path: images/model