development:
    :salt_length: 10
    :ticket_state_change_days: 14
    :upload_attachment:
        :path: uploads/attachments
    :upload_image:
        :path: images/model
        :width: 464
        :height: 174
        :thumb_width: 212
        :thumb_height: 80
    :culture_bus_link: "http://www.malmo.se/kulturbibliotek/malmokulturstod/kulturforbarnochunga/kulturbussarna.4.3101c0911206abdf073800025491.html"
    :ldap:
        :address:
        :port: 389
        :base_dn:
        :bind:
            :dn:
            :password:
        :max_search_results: 25
    :allotment:
        :proximity_boundary: 3
    :mailers:
        :from_adress: "Kulturproceduren, Malmö Stad <noreply@malmo.se>"
        :base_url: "localhost:3000"
test:
    :salt_length: 10
    :ticket_state_change_days: 14
    :upload_attachment:
        :path: uploads/attachments
    :upload_image:
        :path: images/model
        :width: 464
        :height: 174
        :thumb_width: 212
        :thumb_height: 80
    :culture_bus_link: "http://www.malmo.se/kulturbibliotek/malmokulturstod/kulturforbarnochunga/kulturbussarna.4.3101c0911206abdf073800025491.html"
    :ldap:
        :address:
        :port: 389
        :base_dn:
        :bind:
            :dn:
            :password:
        :max_search_results: 25
    :allotment:
        :proximity_boundary: 3
    :mailers:
        :from_adress: "Kulturproceduren, Malmö Stad <noreply@malmo.se>"
        :base_url: "localhost:3000"
production:
    :salt_length: 10
    :ticket_state_change_days: 14
    :upload_attachment:
        :path: uploads/attachments
    :upload_image:
        :path: images/model
        :width: 464
        :height: 174
        :thumb_width: 212
        :thumb_height: 80
    :culture_bus_link: "http://www.malmo.se/kulturbibliotek/malmokulturstod/kulturforbarnochunga/kulturbussarna.4.3101c0911206abdf073800025491.html"
    :ldap:
        :address:
        :port: 389
        :base_dn:
        :bind:
            :dn:
            :password:
        :max_search_results: 25
    :allotment:
        :proximity_boundary: 3
    :mailers:
        :from_adress: "Kulturproceduren, Malmö Stad <noreply@malmo.se>"
        :base_url: "localhost:3000"
