common: &common
    :asset_host: "http://www.dev.malmo.se/assets"
    :salt_length: 10
    :request_key_length: 20
    :generated_password_length: 8
    :occasion_reminder_days: 2
    :evaluation_form:
        :activation_days: 2
        :reminder_days: 7
    :ticket_state:
        :group_days: 14
        :district_days: 14
    :upload_attachment:
        :path: uploads/attachments
    :upload_image:
        :path: model
        :width: 454
        :height: 206
        :thumb_width: 204
        :thumb_height: 80
    :kp_external_link: "http://www.dev.malmo.se/kulturproceduren"
    :kp_manual_link: "http://www.dev.malmo.se/kulturproceduren"
    :kbu_link: "http://www.malmo.se/KBU"
    :culture_bus_link: "http://www.malmo.se/kulturbibliotek/malmokulturstod/kulturforbarnochunga/kulturbussarna.4.3101c0911206abdf073800025491.html"
    #:ldap:
    #    :address:
    #    :port: 389
    #    :base_dn:
    #    :bind:
    #        :dn:
    #        :password:
    #    :max_search_results: 25
    #    :username_prefix: "malmoaut-"
    :allotment:
        :proximity_boundary: 3
    :mailers:
        :from_adress: "Kulturproceduren, Malmö Stad <noreply@malmo.se>"
        :debug_recipient: "andreas.johansson@kentor.se"
    :elit_kp_service_endpoint: "http://esb.dev.malmo.se:9080/elit-kpService/elit-kpPort"
        
development:
    <<: *common
    :instance_title: "DEV"
    :evaluation_form:
        :activation_days: 1
        :reminder_days: 1
    :ticket_state:
        :group_days: 1
        :district_days: 1

test:
    <<: *common
release_test:
    <<: *common

production:
    <<: *common
    :asset_host: "http://webapps.malmo.se/assets"
    :kp_external_link: "http://www.malmo.se/kulturproceduren"
    :kp_manual_link: "http://www.malmo.se/kulturproceduren"
    :occasion_reminder_days: 1
    :evaluation_form:
        :activation_days: 1
        :reminder_days: 2
    :ticket_state:
        :group_days: 1
        :district_days: 1

education:
    <<: *common
    :instance_title: "UTB"
    :asset_host: "http://webapps.malmo.se/assets"

